### ISSUE TITLE
English build instructions

### ISSUE THREAD

**Issue by friksa** [guooscar/JazminServer#12]
This looks like an amazing project!!! Wow!

Can you please provide build instructions in English?

Thanks!

Here are the steps taken this far:
git clone the project
When opening the project in IntelliJ on macOS, it complains that the specified Java JVM cannot be found, so set IntelliJ up for Java 1.8.

Run build.xml ant file to build/release and it works fine as far as I can tell.

Now I open terminal and go to JazminServer/JazminServer/release/JazminServer and run
````
chmod +x jazmin
./jazmin start INSTANCE_NAME
>instance INSTANCE_NAME not exist 
````

I am not sure what the INSTANCE_NAME is and how to go from here.

**Comment by guooscar** [comment]
the jazmin shell script is use to run JazminServer on product env.
if you want to debug application you dont need it
just run the demo java files in jazmin/test/server/sip

**Comment by friksa** [comment]
Awesome!  Thanks!
