### ISSUE TITLE
SIP to RTMP

### ISSUE THREAD

**Issue by friksa** [guooscar/JazminServer#13]
We have a conference on a FreeSwitch server and would like to record it with the Wowza server.

Will this project allow us to make a SIP call to the FreeSwitch server and proxy the call to Wowza server as RTMP so that Wowza can record it?

I assume that the UDP RTP packets can go directly from FreeSwitch to Wowza?

If so, can you please provide us an idea how to start?

Thanks so much for an amazing project!!

**Comment by guooscar** [comment]
jazmin.test.server.sip.b2bua.SipApp  is a "back to back user agent " demo application

**Comment by friksa** [comment]
Thanks.  How would you create a SIP client and dial into another server?

**Comment by guooscar** [comment]
1.create ur sip server
2.when u receive a sip request change the SDP content and forward to another server
3.receive the response change SDP content and forward to client

**Comment by friksa** [comment]
Thanks!
