### ISSUE TITLE
webrtc relay demo?

### ISSUE THREAD

**Issue by notedit** [guooscar/JazminServer#16]

**Comment by guooscar** [comment]
try the jazmin/test/server/sip/webrtc/WebRTCB2BUAMessageHandler.java . i tested  this demo  using jssip(http://www.jssip.net/) as client

**Comment by notedit** [comment]
hi  i see this demo it is a sip base  webrtc. 

i want to have a pure  webrtc client relay,    i am not familiar with  sip.  

can  we have a  pure webrtc  client relay?   that will be thankful.

**Comment by guooscar** [comment]
check jazmin.test.server.relay.RelayServerDtlsTest

**Comment by notedit** [comment]
ok  thanks
