### ISSUE TITLE
How to use DAO in a thread

### ISSUE THREAD

**Issue by thomkins** [guooscar/JazminServer#18]
`new Thread(()->{
    userDao.updateUser(userBean);
}).start();`

Connection inside ThreadLocal

`java.lang.IllegalStateException: call begin transcation first
    at jazmin.driver.jdbc.ConnectionDriver.getConnection(ConnectionDriver.java:121)`

**Comment by guooscar** [comment]
DAO CANNOT use in user thread
all jdbc connection is managed by jazmin container.
so if u want to invoke dao ,u should call in action  or controller .
